[Project Euler 114 Problem](https://projecteuler.net/problem=114)

[Project Euler 115 Problem](https://projecteuler.net/problem=115)

## Plan

1. Dynamic programming for any n, m
2. For 114 -- F(3, 50), iterate over F(4, i) until reach 1000000

In [31]:
F_cache = {}

def F(m, n) :
    if m > n :
        return 1
        
    if (m, n) in F_cache :
        return F_cache[(m, n)]
    
    count = 1
    for start in range(n - m + 1) :
        for block_size in range(m, n - start + 1) :
            # print (start, block_size), m, n, count, n - block_size - start - 1
            count += F(m, n - block_size - start - 1)
            
    F_cache[(m, n)] = count
    
    print (m, n), count
    return count

F(3, 7), F(3, 29), F(3, 30), F(10, 56), F(10, 57)

(3, 3) 2
(3, 7) 17
(3, 5) 7
(3, 4) 4
(3, 9) 44
(3, 8) 27
(3, 6) 11
(3, 13) 305
(3, 12) 189
(3, 11) 117
(3, 10) 72
(3, 17) 2091
(3, 16) 1292
(3, 15) 798
(3, 14) 493
(3, 21) 14328
(3, 20) 8855
(3, 19) 5473
(3, 18) 3383
(3, 25) 98209
(3, 24) 60697
(3, 23) 37513
(3, 22) 23184
(3, 29) 673135
(3, 26) 158905
(3, 30) 1089155
(10, 12) 7
(10, 11) 4
(10, 10) 2
(10, 23) 121
(10, 22) 97
(10, 21) 80
(10, 20) 67
(10, 19) 56
(10, 18) 46
(10, 17) 37
(10, 16) 29
(10, 15) 22
(10, 14) 16
(10, 13) 11
(10, 34) 2734
(10, 33) 2128
(10, 32) 1643
(10, 31) 1255
(10, 30) 947
(10, 29) 706
(10, 28) 521
(10, 27) 382
(10, 26) 280
(10, 25) 207
(10, 24) 156
(10, 45) 48319
(10, 44) 36754
(10, 43) 27923
(10, 42) 21220
(10, 41) 16160
(10, 40) 12355
(10, 39) 9497
(10, 38) 7345
(10, 37) 5714
(10, 36) 4465
(10, 35) 3496
(10, 56) 880711
(10, 46) 63380
(10, 57) 1148904

(17, 673135, 1089155, 880711, 1148904)

In [35]:
F(3, 50)

(3, 28) 416020
(3, 27) 257114
(3, 34) 7465176
(3, 33) 4613732
(3, 32) 2851443
(3, 31) 1762289
(3, 38) 51167077
(3, 37) 31622993
(3, 36) 19544085
(3, 35) 12078909
(3, 42) 350704367
(3, 41) 216747219
(3, 40) 133957148
(3, 39) 82790070
(3, 46) 2403763488
(3, 45) 1485607536
(3, 44) 918155951
(3, 43) 567451585
(3, 50) 16475640049

16475640049

In [34]:
for i in range(200) :
    print i, F(50, i)

 0 1
1 1
2 1
3 1
4 1
5 1
6 1
7 1
8 1
9 1
10 1
11 1
12 1
13 1
14 1
15 1
16 1
17 1
18 1
19 1
20 1
21 1
22 1
23 1
24 1
25 1
26 1
27 1
28 1
29 1
30 1
31 1
32 1
33 1
34 1
35 1
36 1
37 1
38 1
39 1
40 1
41 1
42 1
43 1
44 1
45 1
46 1
47 1
48 1
49 1
50 2
51 4
52 7
53 11
54 16
55 22
56 29
57 37
58 46
59 56
60 67
61 79
62 92
63 106
64 121
65 137
66 154
67 172
68 191
69 211
70 232
71 254
72 277
73 301
74 326
75 352
76 379
77 407
78 436
79 466
80 497
81 529
82 562
83 596
84 631
85 667
86 704
87 742
88 781
89 821
90 862
91 904
92 947
93 991
94 1036
95 1082
96 1129
97 1177
98 1226
99 1276
100 1327
101 1380
102 1437
103 1501
104 1576
105 1667
106 1780
107 1922
108 2101
109 2326
110 2607
111 2955
112 3382
113 3901
114 4526
115 5272
116 6155
117 7192
118 8401
119 9801
120 11412
121 13255
122 15352
123 17726
124 20401
125 23402
126 26755
127 30487
128 34626
129 39201
130 44242
131 49780
132 55847
133 62476
134 69701
135 77557
136 86080
137 95307
138 105276
139 116026
140 127597
141 140030
142 153367
143 167651
144 182926
145 199237
146 216630
147 235152
148 254851
149 275776
150 297977
151 321505
152 346413
153 372758
154 400604
155 430026
156 461115
157 493984
158 528775
159 565667
160 604885
161 646710
162 691490
163 739652
164 791715
165 848304
166 910165
167 978181
168 1053389
169 1136998
170 1230408
171 1335230
172 1453307
173 1586736
174 1737891
175 1909447
176 2104405
177 2326118
178 2578318
179 2865144
180 3191171
181 3561440
182 3981489
183 4457385
184 4995757
185 5603830
186 6289460
187 7061170
188 7928187
189 8900480
190 9988799
191 11204715
192 12560661
193 14069974
194 15746938
195 17606828
196 19665955
197 21941712
198 24452621
199 27218381